from .NumberExpressions.NumberExpressionBase import NumberExpressionBase
from .StringExpressions.StringExpressionBase import StringExpressionBase
from .BooleanExpressions.BooleanExpressionBase import BooleanExpressionBase
from .InstructionExpressions.InstuctionExpressionBase import InstructionExpressionBase

from .NumberExpressions.NumberValue import NumberValue
from .NumberExpressions.NumberNegativeValue import NumberNegativeValue
from .NumberExpressions.NumberVariable import NumberVariable
from .NumberExpressions.NumberReadInputOperation import NumberReadInputOperation
from .NumberExpressions.NumberSimpleOperation import NumberSimpleOperation
from .NumberExpressions.StringLengthFunction import StringLengthFunction
from .NumberExpressions.StringPositionFunction import StringPositionFunction

from .StringExpressions.StringValue import StringValue
from .StringExpressions.StringVariable import StringVariable
from .StringExpressions.StringReadInputOperation import StringReadInputOperation
from .StringExpressions.StringConcatenateFunction import StringConcatenateFunction
from .StringExpressions.StringSubstringFunction import StringSubstringFunction

from .BooleanExpressions.BooleanValue import BooleanValue
from .BooleanExpressions.BooleanNumberComparsionOperation import BooleanNumberComparsionOperation
from .BooleanExpressions.BooleanStringComparsionOperation import BooleanStringComparsionOperation
from .BooleanExpressions.BooleanConcatenationOperation import BooleanConcatenationOperation
from .BooleanExpressions.BooleanNegativeValue import BooleanNegativeValue

from .InstructionExpressions.ExitInstruction import ExitInstruction
from .InstructionExpressions.AssignNumberInstruction import AssignNumberInstruction
from .InstructionExpressions.AssignStringInstruction import AssignStringInstruction
from .InstructionExpressions.PrintNumberFunction import PrintNumberFunction
from .InstructionExpressions.PrintStringFunction import PrintStringFunction
from .InstructionExpressions.IfElseExpression import IfElseExpression
from .InstructionExpressions.IfExpression import IfExpression
from .InstructionExpressions.InstructionPair import InstructionPair
from .InstructionExpressions.WhileExpression import WhileExpression
from .InstructionExpressions.UntilExpression import UntilExpression
from .InstructionExpressions.NoOperation import NoOperation

debug_enabled = False